version: '3.1'

services:
  jrtb-db:
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_DATABASE: 'dev_jrtb_db'

      MYSQL_USER: 'dev_jrtb_db_user'

      MYSQL_PASSWORD: 'dev_jrtb_password'

      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3308'
